import Foundation


public enum ControlChange {
  enum Error: LocalizedError {
    case missingData
    
    var errorDescription: String {
      switch self {
      case .missingData:
        return "There is insufficiant data for this control change."
      }
    }
  }
  
  case bankSelectMSB(msb: ControlChangeValue)
  case modulation(msb: ControlChangeValue)
  case breathController(msb: ControlChangeValue)
  case cc3(msb: ControlChangeValue)
  case footController(msb: ControlChangeValue)
  case portamentoTime(msb: ControlChangeValue)
  case coarseDataEntry(msb: ControlChangeValue)
  case channelVolume(msb: ControlChangeValue)
  case balance(msb: ControlChangeValue)
  case cc9(msb: ControlChangeValue)
  case pan(msb: ControlChangeValue)
  case expressionController(msb: ControlChangeValue)
  case effectControl1(msb: ControlChangeValue)
  case effectControl2(msb: ControlChangeValue)
  case cc14(msb: ControlChangeValue)
  case cc15(msb: ControlChangeValue)
  case generalPurposeController1(msb: ControlChangeValue)
  case generalPurposeController2(msb: ControlChangeValue)
  case generalPurposeController3(msb: ControlChangeValue)
  case generalPurposeController4(msb: ControlChangeValue)
  case cc20(msb: ControlChangeValue)
  case cc21(msb: ControlChangeValue)
  case cc22(msb: ControlChangeValue)
  case cc23(msb: ControlChangeValue)
  case cc24(msb: ControlChangeValue)
  case cc25(msb: ControlChangeValue)
  case cc26(msb: ControlChangeValue)
  case cc27(msb: ControlChangeValue)
  case cc28(msb: ControlChangeValue)
  case cc29(msb: ControlChangeValue)
  case cc30(msb: ControlChangeValue)
  case cc31(msb: ControlChangeValue)
  
  case fineBankSelect(lsb: ControlChangeValue)
  case fineModulation(lsb: ControlChangeValue)
  case fineBreathController(lsb: ControlChangeValue)
  case fineCC3(lsb: ControlChangeValue)
  case finefootController(lsb: ControlChangeValue)
  case finePortamentoTime(lsb: ControlChangeValue)
  case fineDataEntry(lsb: ControlChangeValue)
  case fineChannelVolume(lsb: ControlChangeValue)
  case fineBalance(lsb: ControlChangeValue)
  case fineCC9(lsb: ControlChangeValue)
  case finePan(lsb: ControlChangeValue)
  case fineExpressionController(lsb: ControlChangeValue)
  case fineEffectControl1(lsb: ControlChangeValue)
  case fineEffectControl2(lsb: ControlChangeValue)
  case fineCC14(lsb: ControlChangeValue)
  case fineCC15(lsb: ControlChangeValue)
  case fineGeneralPurposeController1(lsb: ControlChangeValue)
  case fineGeneralPurposeController2(lsb: ControlChangeValue)
  case fineGeneralPurposeController3(lsb: ControlChangeValue)
  case fineGeneralPurposeController4(lsb: ControlChangeValue)
  case fineCC20(lsb: ControlChangeValue)
  case fineCC21(lsb: ControlChangeValue)
  case fineCC22(lsb: ControlChangeValue)
  case fineCC23(lsb: ControlChangeValue)
  case fineCC24(lsb: ControlChangeValue)
  case fineCC25(lsb: ControlChangeValue)
  case fineCC26(lsb: ControlChangeValue)
  case fineCC27(lsb: ControlChangeValue)
  case fineCC28(lsb: ControlChangeValue)
  case fineCC29(lsb: ControlChangeValue)
  case fineCC30(lsb: ControlChangeValue)
  case fineCC31(lsb: ControlChangeValue)
  
  case sustain(onOff: ControlChangeValue)
  case portamento(onOff: ControlChangeValue)
  case sostenuto(onOff: ControlChangeValue)
  case soft(onOff: ControlChangeValue)
  case legato(onOff: ControlChangeValue)
  case hold2(onOff: ControlChangeValue)
  
  case soundController1(value: ControlChangeValue)
  case soundController2(value: ControlChangeValue)
  case soundController3(value: ControlChangeValue)
  case soundController4(value: ControlChangeValue)
  case soundController5(value: ControlChangeValue)
  case soundController6(value: ControlChangeValue)
  case soundController7(value: ControlChangeValue)
  case soundController8(value: ControlChangeValue)
  case soundController9(value: ControlChangeValue)
  case soundController10(value: ControlChangeValue)
  case generalPurposeController5(value: ControlChangeValue)
  case generalPurposeController6(value: ControlChangeValue)
  case generalPurposeController7(value: ControlChangeValue)
  case generalPurposeController8(value: ControlChangeValue)
  case portamentoControl(value: ControlChangeValue)
  case cc85(value: ControlChangeValue)
  case cc86(value: ControlChangeValue)
  case cc87(value: ControlChangeValue)
  case highResolutionVelocityPrefix(lsb: ControlChangeValue)
  case cc89(value: ControlChangeValue)
  case cc90(value: ControlChangeValue)
  
  case effects1Depth(value: ControlChangeValue)
  case effects2Depth(value: ControlChangeValue)
  case effects3Depth(value: ControlChangeValue)
  case effects4Depth(value: ControlChangeValue)
  case effects5Depth(value: ControlChangeValue)
  case dataIncrement(unused: ControlChangeValue)
  case dataDecrement(unused: ControlChangeValue)
  case nonRegisteredParameterNumberLSB(lsb: ControlChangeValue)
  case nonRegisteredParameterNumberMSB(msb: ControlChangeValue)
  case registeredParameterNumberLSB(lsb: ControlChangeValue)
  case registeredParameterNumberMSB(msb: ControlChangeValue)
  case cc102(value: ControlChangeValue)
  case cc103(value: ControlChangeValue)
  case cc104(value: ControlChangeValue)
  case cc105(value: ControlChangeValue)
  case cc106(value: ControlChangeValue)
  case cc107(value: ControlChangeValue)
  case cc108(value: ControlChangeValue)
  case cc109(value: ControlChangeValue)
  case cc110(value: ControlChangeValue)
  case cc111(value: ControlChangeValue)
  case cc112(value: ControlChangeValue)
  case cc113(value: ControlChangeValue)
  case cc114(value: ControlChangeValue)
  case cc115(value: ControlChangeValue)
  case cc116(value: ControlChangeValue)
  case cc117(value: ControlChangeValue)
  case cc118(value: ControlChangeValue)
  case cc119(value: ControlChangeValue)
  
  case allSoundOff(unused: ControlChangeValue)
  case resetAllControllers(unused: ControlChangeValue)
  case localControl(onOff: ControlChangeValue)
  case allNotesOff(unused: ControlChangeValue)
  case omniModeOff(unused: ControlChangeValue)
  case omniModeOn(unused: ControlChangeValue)
  case monoModeOn(value: ControlChangeValue)
  case polyModeOn(unused: ControlChangeValue)
  
  init(controlType: DataByte, data: DataByte) throws {
    let ccValue = ControlChangeValue(data)
    switch controlType.value {
    case 0: self = .bankSelectMSB(msb: ccValue)
    case 1: self = .modulation(msb: ccValue)
    case 2: self = .breathController(msb: ccValue)
    case 3: self = .cc3(msb: ccValue)
    case 4: self = .footController(msb: ccValue)
    case 5: self = .portamentoTime(msb: ccValue)
    case 6: self = .coarseDataEntry(msb: ccValue)
    case 7: self = .channelVolume(msb: ccValue)
    case 8: self = .balance(msb: ccValue)
    case 9: self = .cc9(msb: ccValue)
    case 10: self = .pan(msb: ccValue)
    case 11: self = .expressionController(msb: ccValue)
    case 12: self = .effectControl1(msb: ccValue)
    case 13: self = .effectControl2(msb: ccValue)
    case 14: self = .cc14(msb: ccValue)
    case 15: self = .cc15(msb: ccValue)
    case 16: self = .generalPurposeController1(msb: ccValue)
    case 17: self = .generalPurposeController2(msb: ccValue)
    case 18: self = .generalPurposeController3(msb: ccValue)
    case 19: self = .generalPurposeController4(msb: ccValue)
    case 20: self = .cc20(msb: ccValue)
    case 21: self = .cc21(msb: ccValue)
    case 22: self = .cc22(msb: ccValue)
    case 23: self = .cc23(msb: ccValue)
    case 24: self = .cc24(msb: ccValue)
    case 25: self = .cc25(msb: ccValue)
    case 26: self = .cc26(msb: ccValue)
    case 27: self = .cc27(msb: ccValue)
    case 28: self = .cc28(msb: ccValue)
    case 29: self = .cc29(msb: ccValue)
    case 30: self = .cc30(msb: ccValue)
    case 31: self = .cc31(msb: ccValue)
    case 32: self = .fineBankSelect(lsb: ccValue)
    case 33: self = .fineModulation(lsb: ccValue)
    case 34: self = .fineBreathController(lsb: ccValue)
    case 35: self = .fineCC3(lsb: ccValue)
    case 36: self = .finefootController(lsb: ccValue)
    case 37: self = .finePortamentoTime(lsb: ccValue)
    case 38: self = .fineDataEntry(lsb: ccValue)
    case 39: self = .fineChannelVolume(lsb: ccValue)
    case 40: self = .fineBalance(lsb: ccValue)
    case 41: self = .fineCC9(lsb: ccValue)
    case 42: self = .finePan(lsb: ccValue)
    case 43: self = .fineExpressionController(lsb: ccValue)
    case 44: self = .fineEffectControl1(lsb: ccValue)
    case 45: self = .fineEffectControl2(lsb: ccValue)
    case 46: self = .fineCC14(lsb: ccValue)
    case 47: self = .fineCC15(lsb: ccValue)
    case 48: self = .fineGeneralPurposeController1(lsb: ccValue)
    case 49: self = .fineGeneralPurposeController2(lsb: ccValue)
    case 50: self = .fineGeneralPurposeController3(lsb: ccValue)
    case 51: self = .fineGeneralPurposeController4(lsb: ccValue)
    case 52: self = .fineCC20(lsb: ccValue)
    case 53: self = .fineCC21(lsb: ccValue)
    case 54: self = .fineCC22(lsb: ccValue)
    case 55: self = .fineCC23(lsb: ccValue)
    case 56: self = .fineCC24(lsb: ccValue)
    case 57: self = .fineCC25(lsb: ccValue)
    case 58: self = .fineCC26(lsb: ccValue)
    case 59: self = .fineCC27(lsb: ccValue)
    case 60: self = .fineCC28(lsb: ccValue)
    case 61: self = .fineCC29(lsb: ccValue)
    case 62: self = .fineCC30(lsb: ccValue)
    case 63: self = .fineCC31(lsb: ccValue)
    case 64: self = .sustain(onOff: ccValue)
    case 65: self = .portamento(onOff: ccValue)
    case 66: self = .sostenuto(onOff: ccValue)
    case 67: self = .soft(onOff: ccValue)
    case 68: self = .legato(onOff: ccValue)
    case 69: self = .hold2(onOff: ccValue)
    case 70: self = .soundController1(value: ccValue)
    case 71: self = .soundController2(value: ccValue)
    case 72: self = .soundController3(value: ccValue)
    case 73: self = .soundController4(value: ccValue)
    case 74: self = .soundController5(value: ccValue)
    case 75: self = .soundController6(value: ccValue)
    case 76: self = .soundController7(value: ccValue)
    case 77: self = .soundController8(value: ccValue)
    case 78: self = .soundController9(value: ccValue)
    case 79: self = .soundController10(value: ccValue)
    case 80: self = .generalPurposeController5(value: ccValue)
    case 81: self = .generalPurposeController6(value: ccValue)
    case 82: self = .generalPurposeController7(value: ccValue)
    case 83: self = .generalPurposeController8(value: ccValue)
    case 84: self = .portamentoControl(value: ccValue)
    case 85: self = .cc85(value: ccValue)
    case 86: self = .cc86(value: ccValue)
    case 87: self = .cc87(value: ccValue)
    case 88: self = .highResolutionVelocityPrefix(lsb: ccValue)
    case 89: self = .cc89(value: ccValue)
    case 90: self = .cc90(value: ccValue)
    case 91: self = .effects1Depth(value: ccValue)
    case 92: self = .effects2Depth(value: ccValue)
    case 93: self = .effects3Depth(value: ccValue)
    case 94: self = .effects4Depth(value: ccValue)
    case 95: self = .effects5Depth(value: ccValue)
    case 96: self = .dataIncrement(unused: ccValue)
    case 97: self = .dataDecrement(unused: ccValue)
    case 98: self = .nonRegisteredParameterNumberLSB(lsb: ccValue)
    case 99: self = .nonRegisteredParameterNumberMSB(msb: ccValue)
    case 100: self = .registeredParameterNumberLSB(lsb: ccValue)
    case 101: self = .registeredParameterNumberMSB(msb: ccValue)
    case 102: self = .cc102(value: ccValue)
    case 103: self = .cc103(value: ccValue)
    case 104: self = .cc104(value: ccValue)
    case 105: self = .cc105(value: ccValue)
    case 106: self = .cc106(value: ccValue)
    case 107: self = .cc107(value: ccValue)
    case 108: self = .cc108(value: ccValue)
    case 109: self = .cc109(value: ccValue)
    case 110: self = .cc110(value: ccValue)
    case 111: self = .cc111(value: ccValue)
    case 112: self = .cc112(value: ccValue)
    case 113: self = .cc113(value: ccValue)
    case 114: self = .cc114(value: ccValue)
    case 115: self = .cc115(value: ccValue)
    case 116: self = .cc116(value: ccValue)
    case 117: self = .cc117(value: ccValue)
    case 118: self = .cc118(value: ccValue)
    case 119: self = .cc119(value: ccValue)
    case 120: self = .allSoundOff(unused: ccValue)
    case 121: self = .resetAllControllers(unused: ccValue)
    case 122: self = .localControl(onOff: ccValue)
    case 123: self = .allNotesOff(unused: ccValue)
    case 124: self = .omniModeOff(unused: ccValue)
    case 125: self = .omniModeOn(unused: ccValue)
    case 126: self = .monoModeOn(value: ccValue)
    case 127: self = .polyModeOn(unused: ccValue)
    default: fatalError("Control change outside of 7-bit range")
    }
  }
}
